src/Entity/Car.php
<?php
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Class Car
 * @package App\Entity
 * @ORM\Entity
 * @ORM\Table(name="cars")
 * @ORM\HasLifecycleCallbacks
 */
class Car
{
    /**
     * @var int
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $car_id;

    /**
     * @var \DateTime|null
     * @ORM\Column(type="datetime")
     */
    private $car_modified;

    /**
     * @var \DateTime|null
     * @ORM\Column(type="datetime")
     */
    private $car_inserted;

    /**
     * @var boolean|null
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $car_visible;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $car_model;

    /**
     * @var float|null
     * @ORM\Column(type="decimal", scale=2, precision=10, nullable=true)
     */
    private $car_price;

    /**
     * @var Brand|null
     * @ORM\JoinColumn(name="car_brand", referencedColumnName="brand_id")
     * @ORM\ManyToOne(targetEntity="Brand", inversedBy="brand_cars")
     */
    private $car_brand;

    public function  __toString()
    {
        $brandName = $this->car_brand ? $this->car_brand->getBrandName() : "N.A.";
        return "{$brandName} | {$this->car_model}";
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function refreshTimestamps() : void
    {
        $this->car_modified = new \DateTime();
        if ($this->car_inserted==null) {
            $this->car_inserted = new \DateTime();
        }
    }

    /**
     * @return int
     */
    public function getCarId(): int
    {
        return $this->car_id;
    }

    /**
     * @return \DateTime|null
     */
    public function getCarModified(): ?\DateTime
    {
        return $this->car_modified;
    }

    /**
     * @param \DateTime|null $car_modified
     */
    public function setCarModified(?\DateTime $car_modified): void
    {
        $this->car_modified = $car_modified;
    }

    /**
     * @return \DateTime|null
     */
    public function getCarInserted(): ?\DateTime
    {
        return $this->car_inserted;
    }

    /**
     * @param \DateTime|null $car_inserted
     */
    public function setCarInserted(?\DateTime $car_inserted): void
    {
        $this->car_inserted = $car_inserted;
    }

    /**
     * @return bool|null
     */
    public function getCarVisible(): ?bool
    {
        return $this->car_visible;
    }

    /**
     * @param bool|null $car_visible
     */
    public function setCarVisible(?bool $car_visible): void
    {
        $this->car_visible = $car_visible;
    }

    /**
     * @return null|string
     */
    public function getCarModel(): ?string
    {
        return $this->car_model;
    }

    /**
     * @param null|string $car_model
     */
    public function setCarModel(?string $car_model): void
    {
        $this->car_model = $car_model;
    }

    /**
     * @return float|null
     */
    public function getCarPrice(): ?float
    {
        return $this->car_price;
    }

    /**
     * @param float|null $car_price
     */
    public function setCarPrice(?float $car_price): void
    {
        $this->car_price = $car_price;
    }

    /**
     * @return Brand|null
     */
    public function getCarBrand(): ?Brand
    {
        return $this->car_brand;
    }

    /**
     * @param Brand|null $car_brand
     */
    public function setCarBrand(?Brand $car_brand): void
    {
        $this->car_brand = $car_brand;
    }


}

src/Controller/CarsController.php
<?php
namespace App\Controller;

use App\Entity\Car;
use App\Service\ICarService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class CarsController
 * @package App\Controller
 * @Route(path="/cars/")
 */
class CarsController extends AbstractController
{
    /** @var ICarService */
    private $carService;

    public function __construct(ICarService $carService)
    {
        $this->carService = $carService;
    }
    // routes: carlist(brandId?), carshow(carId), cardel(carId), caredit(carId?)


    // /cars/list
    // /cars/list/5  => brandId=5
    // /cars/list?isVisible=false
    /**
     * @param Request $request
     * @param int $brandId
     * @return Response
     * @Route(name="carlist", path="list/{brandId}", requirements={ "brandId": "\d+" } )
     */
    public function listAction(Request $request, $brandId = 0) : Response
    {
        // TODO convert db entities into a ViewModels
        if ($brandId){
            $cars = $this->carService->getCarsByBrand($brandId);
        } else {
            $isVisible = $request->query->getBoolean('isVisible');
            if ($isVisible == null){
                $cars = $this->carService->getAllCars();
            } else {
                $cars = $this->carService->getCarsByVisibility($isVisible);
            }
        }
        return $this->render('cars/carlist.html.twig', ["cars" => $cars]);
    }
    /**
     * @param Request $request
     * @param int $carId
     * @return Response
     * @Route(name="carshow", path="show/{carId}", requirements={ "carId": "\d+" } )
     */
    public function showAction(Request $request, $carId) : Response
    {
        // TODO convert db entity into a viewModel
        $oneCar = $this->carService->getCarById($carId);
        return $this->render('cars/carshow.html.twig', ["car"=>$oneCar]);
    }
    /**
     * @param Request $request
     * @param int $carId
     * @return Response
     * @Route(name="cardel", path="del/{carId}", requirements={ "carId": "\d+" } )
     */
    public function delAction(Request $request, $carId) : Response
    {
        $this->carService->removeCar($carId);
        $this->addFlash('notice', 'CAR REMOVED');
        return $this->redirectToRoute('carlist');
    }
    /**
     * @param Request $request
     * @param int $carId
     * @return Response
     * @Route(name="caredit", path="edit/{carId}", requirements={ "carId": "\d+" } )
     */
    public function editAction(Request $request, $carId = 0) : Response
    {
        // TODO convert db entity into a form DTO
        if ($carId) {
            $oneCar = $this->carService->getCarById($carId);
        } else {
            $oneCar = new Car();
        }

        $form = $this->carService->getCarForm($oneCar);
        $form->handleRequest($request); // $_POST => $oneCar
        if ($form->isSubmitted() && $form->isValid()){
            $this->carService->saveCar($oneCar);
            $this->addFlash('notice', 'CAR SAVED');
            return $this->redirectToRoute('carlist');
        }
        return $this->render('cars/caredit.html.twig', ["form"=>$form->createView()]);
    }
}
/*
 * HOMEWORK: FIND OUT A PROJECT WORK TOPIC
 * - minimum three entities
 * - PLUS user entity
 * - Create the entity classes
 * - Create the data fixtures to load some initial data
 * - Upload your entity classes + data fixture class in one ZIP via Moodle
 */

templates/cars/caredit.html.twig
{% extends 'cars/cars.html.twig' %}

{% block carBody %}
    {% if form is not null and form is not empty %}
        {% form_theme form 'form_table_layout.html.twig' %}
        {{ form_start(form) }}
        {{ form_widget(form) }}
        {{ form_end(form) }}
    {% endif %}
{% endblock %}

templates/cars/carlist.html.twig
{# routes: carlist(brandId?), carshow(carId), cardel(carId), caredit(carId?) #}

{% extends 'cars/cars.html.twig' %}

{# @var cars \App\Entity\Car[] #}

{% block carBody %}
    <h2>LIST OF CARS</h2>
    <p><a href="{{ path('caredit') }}">ADD NEW CAR</a></p>
    <table border="1">
        <tr><th>Brand</th><th>Model</th><th>Datasheet</th><th>Edit</th><th>Remove</th></tr>

        {% for car in cars %}
            {% set brandName = car.carBrand is null ? "N/A" : car.carBrand.brandName %}
            <tr>
                <td>{{ brandName }}</td>
                <td>{{ car.carModel }}</td>
                <td><a href="{{ path('carshow', { 'carId': car.carId }) }}">SHOW</a></td>
                <td><a href="{{ path('caredit', { 'carId': car.carId }) }}">EDIT</a></td>
                <td><a href="{{ path('cardel', { 'carId': car.carId }) }}">DEL</a></td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/cars/cars.html.twig
{# routes: carlist(brandId?), carshow(carId), cardel(carId), caredit(carId?) #}
{# CRUD: Create Read Update Delete #}
{#
    carEntity ( = carDataModel)
    carViewModel
    carDTO for forms
    carDTO for web services/JSON api
    carDomainModel ( = carDataModel + Business Logic)

    ONLY THIS SEMESTER: use carEntity in all layers
#}
{% extends 'base.html.twig' %}

{% block title %}My Car Manager Page{% endblock %}
{% block body %}
    <p><a href="{{ path('carlist') }}">BACK TO THE LIST PAGE</a></p>
    {% block carBody %}
    {% endblock %}
{% endblock %}

templates/cars/carshow.html.twig
{% extends 'cars/cars.html.twig' %}

{# @var car \App\Entity\Car #}
{#
    {{ someDataFromController.someProperty }}
    someDataFromController[someProperty]
    someDataFromController->getSomeProperty()
    someDataFromController->isSomeProperty()
    someDataFromController->hasSomeProperty()
    someDataFromController->$someProperty
#}

{% block carBody %}
   {% set brandName = car.carBrand is null ? "N/A" : car.carBrand.brandName %}
    {% set brandId = car.carBrand is null ? "N/A" : car.carBrand.brandId %}

    <table border="1">
        <tr><td>ID:</td><td>{{ car.carId }}</td></tr>
        <tr><td>MODIFIED:</td><td>{{ car.carModified|date("Y.m.d. H:i:s") }}</td></tr>
        <tr><td>INSERTED:</td><td>{{ car.carInserted|date("Y.m.d. H:i:s") }}</td></tr>
        <tr><td>VISIBLE:</td><td>{{ car.carVisible ? "YES" : "NO" }}</td></tr>
        <tr><td>MODEL:</td><td>{{ car.carModel }}</td></tr>
        <tr><td>PRICE:</td><td>{{ car.carPrice }} EUR</td></tr>
        <tr><td>BRAND:</td><td>
                {{ brandName }}
                <a href="{{ path('carlist', { 'brandId': brandId } )  }}">FILTER FOR BRAND</a>
            </td></tr>
    </table>
{% endblock %}